{{- if .Values.loki.enabled }}
{{- if or .Values.loki.serviceAccount.create .Values.loki.s3.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "loki" .Values.loki.serviceAccount.name }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.loki.labels" . | nindent 4 }}
  {{- with .Values.loki.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

