{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.prometheus.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.prometheus.service.port }}"
  {{- end }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    {{- include "monitoring.prometheus.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}

