{{- if .Values.security.mTLS.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ include "istio.namespace" . }}
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.security.mTLS.mode }}
{{- end }}

