apiVersion: v2
name: postgresql
description: PostgreSQL with Primary-Replica replication
type: application
version: 1.0.0
appVersion: "17"

dependencies:
  - name: postgresql
    version: "15.5.0"
    repository: https://charts.bitnami.com/bitnami
