apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
  namespace: argo-rollouts
type: Opaque
stringData:
  {{- if .Values.notifications.grafana.enabled }}
  # Grafana에서 발급받은 토큰
  grafana-api-key: "GRAFANA_TOKEN"
  {{- end }}

  {{- if .Values.notifications.discord.enabled }}
  # Discord Webhook URL
  discord-webhook-url: "https://discord.com/api/webhooks/1447770723887222855/H8QUSS2p9ZZrApzbhlsdFyjSuhFIjQUiNshZFRrnKUextrP9H2JYsl8arBLOjNmj8bBC"
  {{- end }}