apiVersion: v2
name: redis
description: Redis for caching
type: application
version: 1.0.0
appVersion: "7"

dependencies:
  - name: redis
    version: "19.5.0"
    repository: https://charts.bitnami.com/bitnami
