apiVersion: v2
name: monitoring
description: Grafana Stack for Kubernetes Observability (Alloy, Loki, Prometheus, Tempo, Grafana)
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - monitoring
  - observability
  - grafana
  - prometheus
  - loki
  - tempo
  - alloy

maintainers:
  - name: c4ang-infra team
    email: team@example.com

sources:
  - https://github.com/grafana/alloy
  - https://github.com/grafana/loki
  - https://github.com/prometheus/prometheus
  - https://github.com/grafana/tempo
  - https://github.com/grafana/grafana

