{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.tempo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tempo.service.type }}
  selector:
    {{- include "monitoring.tempo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.tempo.service.tempoPort }}
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: {{ .Values.tempo.service.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.tempo.service.otlpHttpPort }}
      targetPort: otlp-http
      protocol: TCP
{{- end }}

