{{- /*
Kafka Topics for all domains
*/ -}}

{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  partitions: {{ .partitions | default $.Values.defaultPartitions }}
  replicas: {{ .replicas | default $.Values.defaultReplicas }}
  config:
    retention.ms: {{ .retentionMs | default $.Values.defaultRetentionMs }}
{{- end }}