apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k6-loadtest.fullname" . }}-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k6-loadtest.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Owner credentials
  OWNER_EMAIL: {{ .Values.testData.owner.email | quote }}
  OWNER_PASSWORD: {{ .Values.testData.owner.password | quote }}
  OWNER_USERNAME: {{ .Values.testData.owner.username | quote }}
  # Customer credentials
  CUSTOMER_EMAIL: {{ .Values.testData.customer.email | quote }}
  CUSTOMER_PASSWORD: {{ .Values.testData.customer.password | quote }}
  CUSTOMER_USERNAME: {{ .Values.testData.customer.username | quote }}
